# Generated by Django 5.0.7 on 2024-11-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(default='Default Description'),
            preserve_default=False,
        ),
    ]
