# Generated by Django 5.0.7 on 2024-11-26 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0001_initial'),
        ('games', '0004_remove_videogame_image_videogame_image_base64'),
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='dlc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='dlc.dlc'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='games.videogame'),
        ),
    ]
