# Generated by Django 5.0.7 on 2024-11-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0003_alter_videogame_mac_graphics_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('content', models.TextField()),
                ('image_base64', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlc', to='games.videogame')),
            ],
        ),
    ]
