# Generated by Django 5.0.7 on 2024-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlc',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
