# Generated by Django 5.0.7 on 2024-11-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0002_alter_dlc_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlc',
            old_name='title',
            new_name='name',
        ),
    ]
