# Generated by Django 5.0.7 on 2024-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_videogame_mac_graphics_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='image',
        ),
        migrations.AddField(
            model_name='videogame',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
